/**
 * Regenerate `docs/bundle-size.md` from the declared budgets and a live measurement.
 * Run with `pnpm run bundle:update`.
 *
 * The published table used to be hand-kept beside a test that owned the real numbers, and it drifted
 * exactly as far as that arrangement allows: `@totalfinance/math` published at "< 14 KB" against a 33 KB
 * budget, `black-scholes` at "< 8 KB" against 8.5, and six budgeted entrypoints — including the
 * umbrella, the largest number in the library — missing from the page altogether.
 *
 * Budgets and intents come from `tools/bundle-size/budgets.ts`, the same record `budgets.test.ts`
 * enforces, so the page cannot disagree with CI about what the contract is.
 */

import { fileURLToPath } from 'node:url';
import { KB, measureBundle } from './bundle-size/measure.js';
import { BUNDLE_BUDGETS, type BundleBudget } from './bundle-size/budgets.js';
import { workspaceAlias } from './bundle-size/workspace-alias.js';
import { writeGenerated } from './write-generated.js';

const root = (path: string): string => fileURLToPath(new URL(`../${path}`, import.meta.url));

/** One KB figure, to a tenth. */
function kb(bytes: number): string {
  return `${(bytes / KB).toFixed(1)} KB`;
}

function budgetLabel(budget: BundleBudget): string {
  return `< ${budget.budgetKB} KB`;
}

export async function buildBundleSizeDoc(): Promise<string> {
  const alias = workspaceAlias();
  const rows: { budget: BundleBudget; gzip: number }[] = [];
  for (const budget of BUNDLE_BUDGETS) {
    const measured = await measureBundle(root(budget.entry), alias);
    rows.push({ budget, gzip: measured.bytesGzip });
  }

  const table = [
    '| Entrypoint | gzip | Budget | Notes |',
    '| --- | ---: | ---: | --- |',
    ...rows.map(
      ({ budget, gzip }) =>
        `| \`${budget.specifier}\` | ${kb(gzip)} | ${budgetLabel(budget)} | ${budget.intent} |`,
    ),
  ].join('\n');

  const guarantees = BUNDLE_BUDGETS.flatMap((budget) =>
    (budget.forbidden ?? []).map(
      (rule) =>
        `- **\`${budget.specifier}\` bundles no \`${rule.needle}\`.** ${rule.why[0]!.toUpperCase()}${rule.why.slice(1)}.`,
    ),
  ).join('\n');

  const rationales = BUNDLE_BUDGETS.filter((budget) => budget.rationale)
    .map((budget) => `### \`${budget.specifier}\` — ${budgetLabel(budget)}\n\n${budget.rationale!}`)
    .join('\n\n');

  return `# Bundle size report

<!-- Generated by tools/bundle-size-doc.ts — do not edit by hand. Run \`pnpm run bundle:update\`. -->

TotalFinance treats bundle size as a public contract (spec §21.5). Every budget below is enforced by a
test that imports exactly that entrypoint and measures the tree-shaken, minified, gzip output
(\`tools/bundle-size\`). A budget cannot be claimed without such a test, and this page is generated
from the same declarations the test enforces — so it cannot quote a budget CI does not hold.

The \`gzip\` column is a measurement taken when this page was generated; it moves with the code and is
allowed to. The \`Budget\` column is the contract.

${table}

## Structural guarantees

These are enforced, not merely measured — the byte count is the lesser half of the claim.

${guarantees}

## Why the budgets are what they are

${rationales}

Budgets may change as features land, but regressions are always visible: the test fails.
`;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const out = root('docs/bundle-size.md');
  await writeGenerated(out, await buildBundleSizeDoc());
  process.stdout.write(`wrote ${out} (${BUNDLE_BUDGETS.length} budgeted entrypoints)\n`);
}
