/**
 * Regenerate `docs/bundle-size.md` from the declared budgets and a live measurement.
 * Run with `pnpm run bundle:update`.
 *
 * The published table used to be hand-kept beside a test that owned the real numbers, and it drifted
 * exactly as far as that arrangement allows: `@totalfinance/math` published at "< 14 KB" against a 33 KB
 * budget, `black-scholes` at "< 8 KB" against 8.5, and six budgeted entrypoints — including the
 * umbrella, the largest number in the library — missing from the page altogether.
 *
 * Budgets and intents come from `tools/bundle-size/budgets.ts`, the same record `budgets.test.ts`
 * enforces, so the page cannot disagree with CI about what the contract is.
 */

import { fileURLToPath } from 'node:url';
import { KB, measureBundle } from './bundle-size/measure.js';
import { BUNDLE_BUDGETS, type BundleBudget } from './bundle-size/budgets.js';
import { workspaceAlias } from './bundle-size/workspace-alias.js';
import { writeGenerated } from './write-generated.js';
import { measurePackedReport, renderConsumerReport } from './bundle-size/packed-report.js';
import { CONSUMER_IMPORT_TOLERANCE_BYTES } from './bundle-size/consumer-fixtures.js';

const root = (path: string): string => fileURLToPath(new URL(`../${path}`, import.meta.url));

/** One KB figure, to a tenth. */
function kb(bytes: number): string {
  return `${(bytes / KB).toFixed(1)} KB`;
}

function budgetLabel(budget: BundleBudget): string {
  return `< ${budget.budgetKB} KB`;
}

export async function buildBundleSizeDoc(): Promise<string> {
  const consumers = await measurePackedReport();
  const alias = workspaceAlias();
  const rows: { budget: BundleBudget; gzip: number }[] = [];
  for (const budget of BUNDLE_BUDGETS) {
    const measured = await measureBundle(root(budget.entry), alias);
    rows.push({ budget, gzip: measured.bytesGzip });
  }

  const table = [
    '| Entrypoint | gzip | Budget | Notes |',
    '| --- | ---: | ---: | --- |',
    ...rows.map(
      ({ budget, gzip }) =>
        `| \`${budget.specifier}\` | ${kb(gzip)} | ${budgetLabel(budget)} | ${budget.intent} |`,
    ),
  ].join('\n');

  const guarantees = BUNDLE_BUDGETS.flatMap((budget) =>
    (budget.forbidden ?? []).map(
      (rule) =>
        `- **\`${budget.specifier}\` bundles no \`${rule.needle}\`.** ${rule.why[0]!.toUpperCase()}${rule.why.slice(1)}.`,
    ),
  ).join('\n');

  const rationales = BUNDLE_BUDGETS.filter((budget) => budget.rationale)
    .map((budget) => `### \`${budget.specifier}\` — ${budgetLabel(budget)}\n\n${budget.rationale!}`)
    .join('\n\n');

  return `# Bundle size report

<!-- Generated by tools/bundle-size-doc.ts — do not edit by hand. Run \`pnpm run bundle:update\`. -->

TotalFinance treats bundle size as a public contract (spec §21.5). Two different measurements below
answer different questions. Both are generated from the same fixture/budget records CI enforces.
Sizes use 1024 bytes per KiB (the historical whole-entrypoint table labels these units KB).

## Small installed consumers

These measurements pack the built packages, install them outside the workspace, and bundle a
consumer that uses only the named calculation. No source aliases, forced side-effect overrides,
or injected pure annotations are used. esbuild ${consumers[0]!.esbuild.bundlerVersion} and Rollup
${consumers[0]!.rollup.bundlerVersion} perform tree shaking; esbuild minifies Rollup's finished
output without rebundling. The fixtures expose a callable with runtime inputs so a constant answer
cannot replace the calculation. This is a local package-artifact measurement, not an npm publication
receipt or a promise for every bundler version/configuration.

${renderConsumerReport(consumers)}

\`normal\` means \`normalCdf\`; \`rsi\` means the RSI indicator; \`facade\` means
\`blackScholes.call\`; expert fixtures name their model's standalone price function.
The source fixture record is \`tools/bundle-size/consumer-fixtures.ts\`. The installed-package
matrix also checks scoped roots, umbrella domain subpaths, direct static namespace imports,
unused-library removal, dynamic-namespace retention, numerical outputs, and typed malformed-input
refusals. Portable import spellings must stay within ${CONSUMER_IMPORT_TOLERANCE_BYTES} gzip bytes
of their feature fixture and retain the same allowed implementation modules.

Root namespace re-exports such as \`import { math } from 'totalfinance'\` can retain the whole
domain in esbuild ([upstream limitation](https://github.com/evanw/esbuild/issues/1420)); Rollup's
corresponding fixtures must remain lean. Use \`import { normalCdf } from 'totalfinance/math'\`
or \`import { normalCdf } from '@totalfinance/math/normal'\` for the portable small-bundle path.
The direct hoist \`import { blackScholes } from 'totalfinance'\` is tested separately from
\`options.blackScholes\`. Dynamic property selection and enumeration legitimately retain more code.
See [imports and bundles](./guides/imports-and-bundles.md) for installation, browser, and Node guidance.

## Whole-entrypoint ceilings

These older budgets bundle an entire source entrypoint, preserving ALL of its exports, with
workspace-source aliases. They protect package/feature ceilings and structural boundaries; they
are **not** the cost of importing one function. A facade includes its callable/explain methods,
runtime guards and diagnostics; an indicator includes its streaming/serialization support.

The \`gzip\` column is a measurement taken when this page was generated; it moves with the code and is
allowed to. The \`Budget\` column is the contract.

${table}

## Structural guarantees

These are enforced, not merely measured — the byte count is the lesser half of the claim.

${guarantees}

## Why the budgets are what they are

${rationales}

Budgets may change as features land, but regressions are always visible: the test fails.
`;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const out = root('docs/bundle-size.md');
  await writeGenerated(out, await buildBundleSizeDoc());
  process.stdout.write(`wrote ${out} (${BUNDLE_BUDGETS.length} budgeted entrypoints)\n`);
}
