/**
 * Phase 3B.N8-DOCS item 4 — the registry of generated documentation.
 *
 * "Update generators and templates before generated output. Hand-editing generated package READMEs,
 * TA references, API reports, TypeDoc output, schemas, or `llms*.txt` is not a closeout."
 *
 * That rule needs an answer to a question nothing in the repository could answer: which files ARE
 * generated, and by what? The docs inventory first guessed from a `<!-- Generated by … -->` marker,
 * and the guess was wrong three ways at once — three TA reference docs emit no marker at all and were
 * attributed to a human owner, `talib-coverage.md` writes `GENERATED` in capitals and missed a
 * case-sensitive regex, and the API reports were never walked. Four of the twenty-one generated
 * documents in this repository were unaccounted for, which is precisely where a hand-edit would go
 * unnoticed.
 *
 * So ownership is DECLARED here, once, and the docs inventory reads it instead of inferring. An entry
 * carrying `build` can be proved byte-for-byte by `generated-docs.test.ts`; the API reports carry none
 * because `pnpm run api:check` already proves them against the compiled `.d.ts`, and duplicating that
 * in a weaker form would be worse than pointing at it.
 */

import { readdirSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildReadmes } from './readme-gen.js';
import { buildLlmsDocs } from './llms-docs.js';
import { taIndicatorsMarkdown } from './ta-registry-doc.js';
import { taCompatibilityMarkdown } from './ta-compatibility-doc.js';
import { taWarmupMarkdown } from './ta-warmup-doc.js';
import { talibCoverageMarkdown } from './ta-talib-coverage-doc.js';
import { readFileSync } from 'node:fs';
import { buildFieldReference } from './fields-doc.js';

const ROOT = fileURLToPath(new URL('..', import.meta.url));

export interface GeneratedDoc {
  /** Repository-relative path of the generated file. */
  path: string;
  /** The generator that owns it, repository-relative. */
  generator: string;
  /**
   * The document's content, before formatting — `undefined` when a stronger check already owns it.
   * The drift test formats this and compares it to disk.
   */
  build?: () => string;
}

/** Every generated documentation surface, with the generator that owns it. */
export function generatedDocs(): GeneratedDoc[] {
  const docs: GeneratedDoc[] = [];

  for (const { dir } of buildReadmes()) {
    docs.push({
      path: `packages/${dir}/README.md`,
      generator: 'tools/readme-gen.ts',
      // Proven by `readme-gen.test.ts`, which compares each README to `buildReadmes()` directly.
    });
  }

  docs.push(
    {
      path: 'docs/llms.txt',
      generator: 'tools/llms-docs.ts',
      // Proven by `llms-docs.test.ts`.
    },
    { path: 'docs/llms-full.txt', generator: 'tools/llms-docs.ts' },
    {
      path: 'docs/guides/ta-indicators.md',
      generator: 'tools/ta-registry-doc.ts',
      build: taIndicatorsMarkdown,
    },
    {
      path: 'docs/guides/ta-compatibility.md',
      generator: 'tools/ta-compatibility-doc.ts',
      build: taCompatibilityMarkdown,
    },
    {
      path: 'docs/guides/ta-warmup.md',
      generator: 'tools/ta-warmup-doc.ts',
      build: taWarmupMarkdown,
    },
    {
      path: 'docs/compatibility/talib-coverage.md',
      generator: 'tools/ta-talib-coverage-doc.ts',
      build: talibCoverageMarkdown,
    },
    {
      path: 'docs/bundle-size.md',
      generator: 'tools/bundle-size-doc.ts',
      // No `build`: the page publishes MEASURED byte counts, which move with any code change. An
      // exact comparison would fail on unrelated commits and teach everyone to regenerate blindly.
      // `bundle-size-doc.test.ts` owns it instead — exact on the contract (entrypoints, budgets,
      // intents, guarantees), tolerant on the measurements.
    },
  );

  // Stage 4.7 slice 3: the field reference — the index and one page per package, generated from the
  // committed declaration walk. No `build`: `fields-doc.test.ts` proves every page byte for byte.
  const fields = buildFieldReference(
    readFileSync(resolve(ROOT, 'tools/manifest/public-contracts.json'), 'utf8'),
  );
  docs.push({ path: 'docs/reference/fields.md', generator: 'tools/fields-doc.ts' });
  for (const page of fields.pages.values()) {
    docs.push({ path: `docs/reference/fields/${page.file}`, generator: 'tools/fields-doc.ts' });
  }

  // The API reports. Enumerated from disk rather than listed, so a new package cannot ship an
  // unowned report. `pnpm run api:check` is the proof; it compares them to the built `.d.ts`.
  const packages = resolve(ROOT, 'packages');
  for (const dir of readdirSync(packages).sort()) {
    const etc = resolve(packages, dir, 'etc');
    if (!existsSync(etc)) continue;
    for (const entry of readdirSync(etc).sort()) {
      if (entry.endsWith('.api.md')) {
        docs.push({ path: `packages/${dir}/etc/${entry}`, generator: 'tools/api-report' });
      }
    }
  }

  return docs.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}

/** Generated path → owning generator. */
export function generatedDocOwners(): Map<string, string> {
  return new Map(generatedDocs().map((doc) => [doc.path, doc.generator]));
}

/** `llms.txt` and `llms-full.txt` share one builder; resolve a path to its content. */
export function buildGenerated(doc: GeneratedDoc): string | null {
  if (doc.build) return doc.build();
  if (doc.path === 'docs/llms.txt') return buildLlmsDocs().concise;
  if (doc.path === 'docs/llms-full.txt') return buildLlmsDocs().full;
  return null;
}
