/**
 * Regenerate the TA-Lib coverage matrix (`docs/compatibility/talib-coverage.md`) from the committed
 * TA-Lib catalog metadata (`packages/technical-analysis/test/golden/talib-meta.json`, emitted by
 * `tools/golden/generate.py`) cross-referenced against the live `@totalfinance/technical-analysis` registry + aliases.
 * Run with `pnpm tsx tools/ta-talib-coverage-doc.ts`.
 */

import { fileURLToPath } from 'node:url';
import { readFileSync } from 'node:fs';
import { writeGenerated } from './write-generated.js';
import { listIndicators } from '../packages/technical-analysis/src/registry.js';
import { ALIAS_TABLE } from '../packages/technical-analysis/src/aliases.js';
import { CDL_ALIASES } from '../packages/technical-analysis/src/candle-aliases.js';

interface MetaFn {
  name: string;
  inputs: Record<string, string | string[]>;
  parameters: Record<string, number>;
  outputs: string[];
}
const metaPath = new URL(
  '../packages/technical-analysis/test/golden/talib-meta.json',
  import.meta.url,
);
const meta = JSON.parse(readFileSync(fileURLToPath(metaPath), 'utf8')) as Record<string, MetaFn[]>;

const reg = new Set(listIndicators().map((x) => x.name));
const regLower = new Map([...reg].map((n) => [n.toLowerCase(), n] as const));
const talibAlias = new Map<string, string>();
for (const row of ALIAS_TABLE) {
  if (!row.talib) continue;
  for (const t of Array.isArray(row.talib) ? row.talib : [row.talib])
    talibAlias.set(t.toUpperCase(), row.totalfinance);
}
const cdl = new Map<string, string>();
for (const [k, v] of Object.entries(CDL_ALIASES)) cdl.set(k.toUpperCase(), v);

// Trivial element-wise libm helpers TA-Lib bundles but that carry no TA semantics.
const TRIVIAL = new Set([
  'ACOS',
  'ASIN',
  'ATAN',
  'CEIL',
  'COS',
  'COSH',
  'EXP',
  'FLOOR',
  'LN',
  'LOG10',
  'SIN',
  'SINH',
  'SQRT',
  'TAN',
  'TANH',
  'ADD',
  'SUB',
  'MULT',
  'DIV',
]);
// MAVP is implemented as the batch function `technical_analysis.mavp(series, periods, opts)` (a per-bar period makes
// a single streaming state ill-defined), so it isn't a registry-listed streaming indicator.
const BATCH_FN: Record<string, string> = { MAVP: 'mavp' };

type Status = { mark: string; totalfinance: string; note: string };
function classify(functionName: string): Status {
  const name = functionName.toUpperCase();
  if (BATCH_FN[name])
    return { mark: '📦', totalfinance: `\`${BATCH_FN[name]}\``, note: 'batch function' };
  if (cdl.has(name))
    return { mark: '✅', totalfinance: `\`${cdl.get(name)!}\``, note: 'candlestick' };
  if (talibAlias.has(name)) {
    const q = talibAlias.get(name)!;
    return { mark: reg.has(q) ? '✅' : '⚠️', totalfinance: `\`${q}\``, note: 'alias' };
  }
  if (regLower.has(name.toLowerCase()))
    return {
      mark: '✅',
      totalfinance: `\`${regLower.get(name.toLowerCase())!}\``,
      note: 'registry',
    };
  if (TRIVIAL.has(name))
    return { mark: '⚪', totalfinance: '—', note: 'trivial element-wise math (out of scope)' };
  return { mark: '❌', totalfinance: '—', note: 'not implemented' };
}

const groups = Object.keys(meta);
let covered = 0;
let trivial = 0;
let total = 0;
const sections: string[] = [];
for (const g of groups) {
  const rows: string[] = [];
  for (const f of meta[g]!) {
    total++;
    const s = classify(f.name);
    if (s.mark === '✅' || s.mark === '📦') covered++;
    else if (s.mark === '⚪') trivial++;
    rows.push(`| \`${f.name}\` | ${s.mark} | ${s.totalfinance} | ${s.note} |`);
  }
  const gCov = meta[g]!.filter((f) => ['✅', '📦'].includes(classify(f.name).mark)).length;
  sections.push(
    `### ${g} — ${gCov}/${meta[g]!.length}\n\n` +
      `| TA-Lib | Status | TotalFinance | Via |\n| --- | :---: | --- | --- |\n${rows.join('\n')}`,
  );
}

const meaningful = total - trivial;
const md =
  `# TA-Lib coverage matrix\n\n` +
  `<!-- GENERATED by tools/ta-talib-coverage-doc.ts — do not edit by hand. -->\n\n` +
  `TotalFinance's \`@totalfinance/technical-analysis\` package cross-referenced against all **${total}** functions in the ` +
  `TA-Lib ${'0.6.x'} C reference. Every value-bearing output is certified against TA-Lib's actual ` +
  `output in \`packages/technical-analysis/test/talib-golden.test.ts\` and \`talib-candles-golden.test.ts\`; ` +
  `intentional convention differences are catalogued in [talib-differences.md](./talib-differences.md).\n\n` +
  `## Summary\n\n` +
  `- **${covered}/${total}** TA-Lib functions implemented` +
  (covered === total
    ? ' — **complete parity**, every group including the element-wise Math Transform/Operator helpers.\n'
    : ` (**${covered}/${meaningful}** of the value-bearing catalog — excluding ${trivial} trivial element-wise math helpers).\n`) +
  `- **${total - covered - trivial}** genuine gaps.\n` +
  `- ✅ implemented (indicator or alias) · 📦 batch-only function` +
  (trivial > 0 ? ' · ⚪ trivial element-wise math (out of scope)' : '') +
  ` · ❌ missing.\n\n` +
  sections.join('\n\n') +
  '\n';

const out = fileURLToPath(new URL('../docs/compatibility/talib-coverage.md', import.meta.url));

/** The document's content, before formatting. Exported so the drift test can compare in memory. */
export function talibCoverageMarkdown(): string {
  return md;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  await writeGenerated(out, talibCoverageMarkdown());
  process.stdout.write(`wrote ${out} (${covered}/${total} covered, ${trivial} trivial)\n`);
}
