/**
 * Phase 3B.N8-DOCS — the documentation naming inventory.
 *
 * The code surface has been inventoried, classified and gated for a whole phase. Documentation had not
 * been, and it is part of the public contract: an example that teaches a field the library does not have
 * is the same class of defect as the wrong field itself, and it reaches the user first.
 *
 * Every documentation surface gets ONE class from the spec's table, because the required treatment
 * differs and a single rule would be wrong for most of them:
 *
 *   future-target       use final vocabulary NOW; a legacy token only inside a before→after explanation
 *   current-runnable    must be truthful against the executable baseline
 *   generated           fix the generator, then regenerate; hand-editing is not a closeout
 *   historical          preserve the exact old identity — it is evidence about what shipped
 *   formula-notation    conventional symbols stay in equations
 *   migration-evidence  before→after tables and search synonyms may name old terms
 *
 * Two rules follow from the classes, and the difference between them is the point of this module:
 *
 *   TRUTHFULNESS (current-runnable, generated) — every identifier a fence presents as library API must
 *     be a name the library actually exports. Checked against the 19,505-name naming baseline, which is
 *     ground truth rather than a heuristic. This is strictly stronger than a token rule in both
 *     directions: it convicts `var`/`iv`/`vols`, which tokenize innocently but do not exist, and it
 *     ACQUITS `k` and `w` in the SSVI fences, which a token rule flags and which are really shipped.
 *
 *   VOCABULARY (future-target) — a spec for unbuilt work is where the next generation of names is
 *     chosen, so it is held to the naming policy itself. There is no baseline to check against yet;
 *     the whole point is to keep `vol: number` from being implemented as `vol`.
 *
 * PROSE is not scanned under either rule. A sentence may say "VaR" or "the ATM vol" — that is how the
 * subject is written, and 3B.N normalized executable identities, never English. Only fenced `ts`/`js`
 * blocks are read, and within them only the positions that assert an API shape.
 *
 * The classes are derived from location and from each document's own declared status, never from a
 * hand-kept list, so a new document is classified the moment it exists. Findings that are legitimate
 * carry an explicit machine-readable disposition in {@link DOCUMENTED_EXCEPTIONS} — the spec rules out a
 * broad file allowlist, and a per-finding entry is what replaces it. A disposition that stops matching
 * anything is itself a failure, so the escape hatch cannot quietly rot into an allowlist.
 */

import { readFileSync, readdirSync, statSync, existsSync, writeFileSync } from 'node:fs';
import { relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import ts from 'typescript';
import { flaggedTokens } from './naming-inventory.js';
import { generatedDocOwners } from '../generated-docs.js';
import { toPublicSpecifier } from '../public-packages.js';

/**
 * Generated path → owning generator, declared in `tools/generated-docs.ts`.
 *
 * Memoized because building it imports every generator. Reading a declared registry replaces what
 * used to be a `<!-- Generated by … -->` marker guess, which missed four of the twenty-one generated
 * documents — three TA references emit no marker, and `talib-coverage.md` writes it in capitals.
 */
let generatedOwners: Map<string, string> | null = null;
function ownerOfGenerated(relativePath: string): string | undefined {
  generatedOwners ??= generatedDocOwners();
  return generatedOwners.get(relativePath);
}

const ROOT = fileURLToPath(new URL('../../', import.meta.url));

export const DOCS_MANIFEST_PATH = fileURLToPath(new URL('./public-docs.json', import.meta.url));

/** The spec's surface classes, verbatim. */
export type DocClass =
  | 'future-target'
  | 'current-runnable'
  | 'generated'
  | 'historical'
  | 'formula-notation'
  | 'migration-evidence';

/** Which rule a class is held to. */
export type DocRule = 'truthfulness' | 'vocabulary' | 'none';

export function ruleFor(documentClass: DocClass): DocRule {
  switch (documentClass) {
    case 'current-runnable':
    case 'generated':
      return 'truthfulness';
    case 'future-target':
      return 'vocabulary';
    // Historical records, before→after tables and equation notation are all cases where naming an old
    // or conventional identity is the document's JOB.
    default:
      return 'none';
  }
}

export interface DocSurface {
  path: string;
  class: DocClass;
  /** The generator that owns it, or `human` — one or the other, never neither. */
  owner: string;
  rule: DocRule;
  /** Fenced ts/js blocks: the executable part of a document. */
  codeFences: number;
}

export interface DocFinding {
  /** Stable identity, so a disposition can name one finding rather than exempting a whole file. */
  id: string;
  path: string;
  class: DocClass;
  rule: DocRule;
  name: string;
  /** Where in the fence the name is asserted as API. */
  position: 'import' | 'access' | 'field' | 'declaration' | 'destructure';
  /** For `vocabulary` findings: the forbidden tokens the name carries. */
  forbidden?: string[];
  /** The fence line, trimmed. */
  line: string;
}

/**
 * Findings that are legitimate, each with the spec's own disposition vocabulary and a reason.
 *
 * Keyed by finding id. An entry that matches nothing fails the gate — that is what keeps this from
 * becoming the file allowlist the spec rules out.
 */
export const DOCUMENTED_EXCEPTIONS: Readonly<
  Record<
    string,
    {
      disposition: 'conventional-formula' | 'search-synonym' | 'illustrative';
      why: string;
      /** Only this generator's named source sections, syntax position and dictionary/declaration. */
      generatedSource?: {
        owner: string;
        headings: readonly string[];
        position: DocFinding['position'];
        containers?: readonly string[];
        line?: string;
      };
    }
  >
> = {
  'docs/guides/http.md#Authorization': {
    disposition: 'illustrative',
    why: 'The authenticated fetch example names the HTTP Authorization header, not a TotalFinance input field. Its bearer value is the server-owned credential.',
  },
  'docs/guides/http.md#randomBytes': {
    disposition: 'illustrative',
    why: 'The credential example imports randomBytes from node:crypto to generate a secure token. This is a Node standard-library export, not a TotalFinance API.',
  },
  'docs/llms-full.txt#AAPL': {
    disposition: 'illustrative',
    why: 'Generated createMarketSnapshot and portfolioSnapshot source JSDoc uses AAPL as an instrument-keyed observations.spots/volatilities dictionary entry, not a declared TotalFinance field.',
    generatedSource: {
      owner: 'tools/llms-docs.ts',
      headings: [
        '@totalfinance/core/artifacts#createMarketSnapshot',
        '@totalfinance/portfolio#portfolioSnapshot',
      ],
      position: 'field',
      containers: ['spots', 'volatilities'],
    },
  },
  'docs/llms-full.txt#AGG': {
    disposition: 'illustrative',
    why: 'Generated allocatePortfolio and proposePortfolioRebalance source JSDoc uses AGG as an instrument id in caller-owned prices, market observations.spots and instrumentClassification dictionaries, not a declared TotalFinance field.',
    generatedSource: {
      owner: 'tools/llms-docs.ts',
      headings: [
        '@totalfinance/portfolio#allocatePortfolio',
        '@totalfinance/portfolio#proposePortfolioRebalance',
      ],
      position: 'field',
      containers: ['prices', 'spots', 'instrumentClassification'],
    },
  },
  'docs/llms-full.txt#SPY': {
    disposition: 'illustrative',
    why: 'Generated allocatePortfolio and proposePortfolioRebalance source JSDoc uses SPY as an instrument id in caller-owned prices, market observations.spots and instrumentClassification dictionaries, not a declared TotalFinance field.',
    generatedSource: {
      owner: 'tools/llms-docs.ts',
      headings: [
        '@totalfinance/portfolio#allocatePortfolio',
        '@totalfinance/portfolio#proposePortfolioRebalance',
      ],
      position: 'field',
      containers: ['prices', 'spots', 'instrumentClassification'],
    },
  },
  'docs/llms-full.txt#USD': {
    disposition: 'illustrative',
    why: 'Generated createMarketSnapshot source JSDoc uses USD as a currency-keyed observations.riskFreeRates dictionary entry, not a declared TotalFinance field.',
    generatedSource: {
      owner: 'tools/llms-docs.ts',
      headings: ['@totalfinance/core/artifacts#createMarketSnapshot'],
      position: 'field',
      containers: ['riskFreeRates'],
    },
  },
  'docs/llms-full.txt#scheme': {
    disposition: 'illustrative',
    why: 'The generated OpenApiDocument declaration retains the OpenAPI HTTP security-scheme bearer member inside a string-keyed host schema; it is not a financial input name.',
    generatedSource: {
      owner: 'tools/llms-docs.ts',
      headings: ['@totalfinance/http#OpenApiDocument'],
      position: 'declaration',
      line: "scheme: 'bearer';",
    },
  },
};

/** A generated-source disposition never exempts the same spelling in another API or position. */
export function matchesDocumentedException(input: {
  path: string;
  owner: string;
  sourceHeading?: string;
  identifier: FenceIdentifier;
}): boolean {
  const entry = DOCUMENTED_EXCEPTIONS[`${input.path}#${input.identifier.name}`];
  if (!entry) return false;
  const scope = entry.generatedSource;
  if (!scope) return true;
  return (
    input.owner === scope.owner &&
    scope.headings.map(toPublicSpecifier).includes(input.sourceHeading ?? '') &&
    input.identifier.position === scope.position &&
    (scope.containers === undefined ||
      scope.containers.includes(input.identifier.container ?? '')) &&
    (scope.line === undefined || scope.line === input.identifier.line)
  );
}

/** Every markdown/text documentation file, plus the package READMEs. */
function documentationFiles(): string[] {
  const out: string[] = [];
  const walk = (dir: string): void => {
    for (const entry of readdirSync(dir).sort()) {
      const path = resolve(dir, entry);
      if (statSync(path).isDirectory()) walk(path);
      else if (entry.endsWith('.md') || entry.endsWith('.txt')) out.push(path);
    }
  };
  walk(resolve(ROOT, 'docs'));
  const packages = resolve(ROOT, 'packages');
  for (const dir of readdirSync(packages).sort()) {
    const readme = resolve(packages, dir, 'README.md');
    if (existsSync(readme)) out.push(readme);
    // The API reports are generated consumer material that item 4 names explicitly, and the walk
    // did not reach them — 15 generated documents outside the inventory entirely.
    const etc = resolve(packages, dir, 'etc');
    if (existsSync(etc)) {
      for (const entry of readdirSync(etc).sort()) {
        if (entry.endsWith('.api.md')) out.push(resolve(etc, entry));
      }
    }
  }
  const rootReadme = resolve(ROOT, 'README.md');
  if (existsSync(rootReadme)) out.push(rootReadme);
  return out;
}

/**
 * Does this spec declare the work SHIPPED?
 *
 * The status sits in a markdown blockquote, so it wraps: five specs write `Status:` at the end of one
 * line and `> **shipped** as ...` on the next, and one writes `**shipped in two waves.**`. Matching the
 * raw text missed all six and quietly held live API documentation to the weaker rule — so the
 * blockquote markers and line breaks are normalized away before looking.
 */
function declaresShipped(text: string): boolean {
  const flattened = text
    .split('\n')
    .map((line) => line.replace(/^\s*>\s?/, ''))
    .join(' ');
  return /Status:\s*\*\*shipped\b/i.test(flattened);
}

/** Classify one surface and name its owner. */
export function classifyDocument(path: string, text: string): { class: DocClass; owner: string } {
  const relativePath = relative(ROOT, path);

  // Generated material is DECLARED, in `tools/generated-docs.ts`, because inferring it did not work:
  // a `<!-- Generated by … -->` marker missed three TA references that emit none and one that writes
  // it in capitals, and attributed all four to a human owner.
  const declaredOwner = ownerOfGenerated(relativePath);
  if (declaredOwner) return { class: 'generated', owner: declaredOwner };

  // A marker still counts, for a generator that has not been added to the registry yet — but the
  // registry gate treats that as a failure rather than a fallback.
  const generatedBy = /^<!--\s*generated by ([^\s]+)/im.exec(text);
  if (generatedBy) return { class: 'generated', owner: generatedBy[1]! };

  // A completed milestone is evidence about what shipped and is never silently rewritten.
  if (relativePath.includes('/milestones/')) return { class: 'historical', owner: 'human' };
  // The naming spec and the decision ledger ARE the before→after record.
  if (/phase-3b-(?:public-naming|decision-ledger)/.test(relativePath)) {
    return { class: 'migration-evidence', owner: 'human' };
  }
  if (relativePath.includes('/formulas/')) return { class: 'formula-notation', owner: 'human' };

  // A spec that declares itself SHIPPED documents a callable API, so its fences are runnable guidance
  // and must be truthful. An unshipped spec is where the next names are chosen, so it is held to the
  // vocabulary instead. Read from the document's own status line rather than from a list.
  if (relativePath.includes('/specs/')) {
    return declaresShipped(text)
      ? { class: 'current-runnable', owner: 'human' }
      : { class: 'future-target', owner: 'human' };
  }

  if (
    relativePath.includes('/guides/') ||
    relativePath.includes('/examples/') ||
    /(?:^|\/)README\.md$/.test(relativePath) ||
    /getting-started\.md$/.test(relativePath)
  ) {
    return { class: 'current-runnable', owner: 'human' };
  }
  return { class: 'future-target', owner: 'human' };
}

/** Every public name the library actually exports — ground truth for the truthfulness rule. */
function shippedNames(): Set<string> {
  const manifest = JSON.parse(
    readFileSync(resolve(ROOT, 'tools/manifest/public-naming.json'), 'utf8'),
  ) as { identities: { name: string }[] };
  return new Set(manifest.identities.map((identity) => identity.name));
}

/**
 * Language and host names, which are not this library's contract.
 *
 * A fence that calls `.toFixed(2)` or `Math.max` is using JavaScript, and holding those to the naming
 * baseline would report the standard library as a defect.
 */
const HOST_OBJECTS: ReadonlySet<string> = new Set([
  'console',
  'Math',
  'JSON',
  'Object',
  'Array',
  'Number',
  'String',
  'Boolean',
  'Date',
  'Promise',
  'Map',
  'Set',
  'process',
  'globalThis',
  'performance',
  'Intl',
  'BigInt',
  'Symbol',
  'Error',
  'RegExp',
  'structuredClone',
  'fetch',
  'crypto',
  'Float64Array',
  'Int32Array',
  'Uint8Array',
  'ArrayBuffer',
  'WeakMap',
  'Reflect',
  'Proxy',
]);

const LANGUAGE_MEMBERS: ReadonlySet<string> = new Set([
  'length',
  'map',
  'filter',
  'reduce',
  'push',
  'slice',
  'toFixed',
  'join',
  'forEach',
  'sort',
  'from',
  'keys',
  'values',
  'entries',
  'log',
  'max',
  'min',
  'absolute',
  'sqrt',
  'exp',
  'pow',
  'round',
  'floor',
  'ceil',
  'stringify',
  'parse',
  'now',
  'toISOString',
  'then',
  'catch',
  'all',
  'includes',
  'indexOf',
  'find',
  'some',
  'every',
  'flat',
  'concat',
  'split',
  'test',
  'has',
  'get',
  'set',
  'add',
  'size',
  'name',
  'message',
  'code',
  'stack',
  'toString',
  'value',
  'done',
  'next',
  'at',
  'fill',
  'reverse',
  'padStart',
  'trim',
  'replace',
  'repeat',
  'sign',
  'sin',
  'cos',
  'tan',
  'random',
  'isFinite',
  'isNaN',
  'hypot',
  'log2',
  'log10',
  'tanh',
  'atan',
  'asin',
  'acos',
  'PI',
  'E',
  'LN2',
  'freeze',
  'assign',
  'fromEntries',
  'toLowerCase',
  'toUpperCase',
  'startsWith',
  'endsWith',
  'charAt',
  'substring',
  'apply',
  'call',
  'bind',
  'constructor',
  'prototype',
  'default',
  'of',
  'isArray',
  'isInteger',
  'trunc',
  'cbrt',
  'sinh',
  'cosh',
  'atan2',
  'expm1',
  'log1p',
  'toLocaleString',
  'toPrecision',
  'valueOf',
  'flatMap',
  'findIndex',
  'lastIndexOf',
  'fromCharCode',
  'charCodeAt',
  'padEnd',
  'matchAll',
  'match',
  'search',
  'normalize',
  'localeCompare',
  'toSorted',
]);

interface FenceIdentifier {
  name: string;
  position: DocFinding['position'];
  line: string;
  /** Immediate object-literal property that owns a dictionary entry, never an arbitrary ancestor. */
  container?: string;
}

/**
 * Identifiers a fence asserts as library API.
 *
 * Only the positions that make a claim about a contract are read. A local `const p = normalCdf(0)` is
 * the author's own variable and asserts nothing about the library, so plain variable declarations are
 * collected as LOCAL and excluded — as are types the fence declares for itself.
 */
function fenceIdentifiers(source: string): FenceIdentifier[] {
  const file = ts.createSourceFile('fence.ts', source, ts.ScriptTarget.ESNext, true);
  const lines = source.split('\n');
  const local = new Set<string>();
  const collectLocal = (node: ts.Node): void => {
    if (
      (ts.isInterfaceDeclaration(node) ||
        ts.isTypeAliasDeclaration(node) ||
        ts.isFunctionDeclaration(node) ||
        ts.isClassDeclaration(node)) &&
      node.name
    ) {
      local.add(node.name.text);
    }
    if (ts.isVariableDeclaration(node) && ts.isIdentifier(node.name)) local.add(node.name.text);
    ts.forEachChild(node, collectLocal);
  };
  collectLocal(file);

  const out: FenceIdentifier[] = [];
  const visit = (node: ts.Node): void => {
    let found: { name: string; position: DocFinding['position'] } | undefined;
    if (ts.isImportSpecifier(node)) {
      found = { name: (node.propertyName ?? node.name).text, position: 'import' };
    } else if (ts.isPropertyAccessExpression(node)) {
      const root = node.expression;
      if (!(ts.isIdentifier(root) && HOST_OBJECTS.has(root.text))) {
        found = { name: node.name.text, position: 'access' };
      }
    } else if (ts.isPropertyAssignment(node) && ts.isIdentifier(node.name)) {
      found = { name: node.name.text, position: 'field' };
    } else if (ts.isPropertySignature(node) && node.name && ts.isIdentifier(node.name)) {
      found = { name: node.name.text, position: 'declaration' };
    } else if (ts.isBindingElement(node)) {
      const bound =
        node.propertyName && ts.isIdentifier(node.propertyName)
          ? node.propertyName
          : ts.isIdentifier(node.name)
            ? node.name
            : undefined;
      if (bound) found = { name: bound.text, position: 'destructure' };
    }
    if (found && !LANGUAGE_MEMBERS.has(found.name) && !local.has(found.name)) {
      const line = file.getLineAndCharacterOfPosition(node.getStart(file)).line;
      const parent = node.parent?.parent;
      const container =
        ts.isPropertyAssignment(node) &&
        parent &&
        ts.isPropertyAssignment(parent) &&
        ts.isIdentifier(parent.name)
          ? parent.name.text
          : undefined;
      out.push({
        ...found,
        ...(container === undefined ? {} : { container }),
        line: (lines[line] ?? '').trim().slice(0, 110),
      });
    }
    ts.forEachChild(node, visit);
  };
  visit(file);
  return out;
}

function executableFences(text: string): { source: string; sourceHeading?: string }[] {
  const fences: { source: string; sourceHeading?: string }[] = [];
  let sourceHeading: string | undefined;
  // One linear scan: generated full docs contain thousands of source sections. A heading inside a
  // matched code fence is consumed with the fence, never interpreted as provenance.
  for (const match of text.matchAll(
    /^(#{1,3}) ([^\n]+)$|```(?:ts|typescript|js|javascript)\n([\s\S]*?)```/gm,
  )) {
    if (match[1] !== undefined) sourceHeading = match[1] === '###' ? match[2] : undefined;
    else
      fences.push({ source: match[3]!, ...(sourceHeading === undefined ? {} : { sourceHeading }) });
  }
  return fences;
}

export interface DocsInventory {
  version: number;
  summary: Record<string, unknown>;
  surfaces: DocSurface[];
  findings: DocFinding[];
  /** Dispositions that matched nothing — stale exemptions, which are themselves a defect. */
  unusedExceptions: string[];
}

export function documentationInventory(): DocsInventory {
  const shipped = shippedNames();
  const surfaces: DocSurface[] = [];
  const findings: DocFinding[] = [];
  const usedExceptions = new Set<string>();

  for (const path of documentationFiles()) {
    const text = readFileSync(path, 'utf8');
    const classified = classifyDocument(path, text);
    const rule = ruleFor(classified.class);
    const fences = executableFences(text);
    const relativePath = relative(ROOT, path);
    surfaces.push({
      path: relativePath,
      class: classified.class,
      owner: classified.owner,
      rule,
      codeFences: fences.length,
    });
    if (rule === 'none') continue;

    for (const fence of fences) {
      for (const identifier of fenceIdentifiers(fence.source)) {
        let forbidden: string[] | undefined;
        if (rule === 'truthfulness') {
          if (shipped.has(identifier.name)) continue;
        } else {
          const flagged = flaggedTokens(identifier.name);
          if (flagged.length === 0) continue;
          forbidden = flagged;
        }
        const id = `${relativePath}#${identifier.name}`;
        if (
          matchesDocumentedException({
            path: relativePath,
            owner: classified.owner,
            ...fence,
            identifier,
          })
        ) {
          usedExceptions.add(id);
          continue;
        }
        // One finding per (file, name) — the same stale field repeated eight times in one document is
        // one repair, and eight rows would just make the artifact harder to read.
        if (findings.some((existing) => existing.id === id)) continue;
        findings.push({
          id,
          path: relativePath,
          class: classified.class,
          rule,
          name: identifier.name,
          position: identifier.position,
          ...(forbidden ? { forbidden } : {}),
          line: identifier.line,
        });
      }
    }
  }

  surfaces.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
  findings.sort((a, b) => (a.id < b.id ? -1 : a.id > b.id ? 1 : 0));

  const byClass = surfaces.reduce<Record<string, number>>(
    (accumulator, surface) => {
      accumulator[surface.class] = (accumulator[surface.class] ?? 0) + 1;
      return accumulator;
    },
    Object.create(null) as Record<string, number>,
  );

  return {
    version: 1,
    summary: {
      surfaces: surfaces.length,
      byClass,
      executableFences: surfaces.reduce((total, surface) => total + surface.codeFences, 0),
      checkedUnderTruthfulness: surfaces.filter((surface) => surface.rule === 'truthfulness')
        .length,
      checkedUnderVocabulary: surfaces.filter((surface) => surface.rule === 'vocabulary').length,
      shippedNamesWatched: shipped.size,
      documentedExceptions: Object.keys(DOCUMENTED_EXCEPTIONS).length,
      findings: findings.length,
    },
    surfaces,
    findings,
    unusedExceptions: Object.keys(DOCUMENTED_EXCEPTIONS)
      .filter((id) => !usedExceptions.has(id))
      .sort(),
  };
}

export function readDocsInventory(): DocsInventory | null {
  try {
    return JSON.parse(readFileSync(DOCS_MANIFEST_PATH, 'utf8')) as DocsInventory;
  } catch {
    return null;
  }
}

export function writeDocsInventory(): DocsInventory {
  const inventory = documentationInventory();
  writeFileSync(DOCS_MANIFEST_PATH, `${JSON.stringify(inventory, null, 2)}\n`, 'utf8');
  return inventory;
}

const isMain = process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href;
if (isMain) {
  const inventory = writeDocsInventory();
  const { summary } = inventory;
  console.log(
    `docs-inventory: ${summary['surfaces']} surfaces ` +
      `(${summary['checkedUnderTruthfulness']} truthfulness, ${summary['checkedUnderVocabulary']} vocabulary), ` +
      `${summary['executableFences']} executable fences, ${summary['findings']} findings`,
  );
  for (const finding of inventory.findings) {
    console.log(`  [${finding.rule}] ${finding.id} (${finding.position}) — ${finding.line}`);
  }
  if (inventory.unusedExceptions.length > 0) {
    console.log(`  STALE dispositions: ${inventory.unusedExceptions.join(', ')}`);
  }
}
